---
- hosts: all
  gather_facts: false
  roles:
  - initialize

- hosts: rke2
  gather_facts: false
  roles:
  - rke2

- hosts: ceph
  gather_facts: false
  roles:
  - ceph

- hosts: kubeclient
  gather_facts: false
  roles:
  - kubernetes