---
- name: mammdoo | initialize | hosts
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    mode: 0644
  tags:
  - initialize
  - initialize_hosts

- name: mammdoo | initialize | apt
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
  - python3
  - python3-pip
  - python3-setuptools
  - python3-wheel
  - htop
  - chrony
  - iptables
  - ufw
  tags:
  - initialize
  - initialize_apt

- name: mammdoo | initialize | chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
    enabled: yes
  tags:
  - initialize
  - initialize_chrony