---
- name: rke2 | config | main
  ansible.builtin.template:
    src: "role.{{ rke2_role }}.config.j2"
    dest: "{{ rke2_dir }}/config/config.yaml"
    mode: 0644
  tags:
  - initialize
  - initialize_rke2
  - initialize_rke2_config

- name: rke2 | config | others
  ansible.builtin.template:
    src: "{{ item }}.config.j2"
    dest: "{{ rke2_dir }}/config/config.yaml.d/{{ item }}.yaml"
    mode: 0644
  with_items:
  - common
  tags:
  - initialize
  - initialize_rke2
  - initialize_rke2_config