---
- name: helm | ingress | intall
  kubernetes.core.helm:
    kubeconfig: utils/kubeconfig
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: 4.12.1
    release_name: ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    release_state: present
  tags:
  - initialize
  - initialize_helm
  - initialize_helm_ingress
  - initialize_helm_ingress_install

