---
- name: kubernetes | operators | namespace
  kubernetes.core.k8s:
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: present
  with_items:
  - mammdoo-base
  tags:
  - initialize
  - initialize_kubernetes
  - initialize_kubernetes_followme

- name: kubernetes | opeators | install
  kubernetes.core.k8s:
    kubeconfig: utils/kubeconfig
    namespace: mammdoo-base
    src: operators/mammdoo.yaml
    state: present
  tags:
  - initialize
  - initialize_kubernetes
  - initialize_kubernetes_followme
