---
- import_tasks: prequisites.yaml

- import_tasks: keyring.yaml

- import_tasks: bootstrap.yaml

- import_tasks: osd.yaml

- import_tasks: kubernetes.yaml
  when: cephadm is defined and kubernetes_ceph_pool_name is defined

- import_tasks: radosgw.yaml

- import_tasks: cleanup.yaml