---
- name: ceph | osd | create
  ansible.builtin.shell:
    cmd: ceph-volume --cluster {{ ceph_name }} lvm create --data {{ item }}
  with_items: "{{ ceph_osd_devices }}"
  tags:
  - initialize
  - initialize_ceph
  - initialize_ceph_osd
  - initialize_ceph_osd_create
